from collections import Counter


def find_the_difference(s: str, t: str) -> str:
    """
    ID: 0389
    Tags:   Hash Table, String, Bit Manipulation, Sorting
    Time:   O(N)
    Memory: O(N)

    Task
    ----------
    You are given two strings s and t.

    String t is generated by random shuffling string s and then add one more letter at a random position.

    Return the letter that was added to t.

    Parameters
    ----------
    s : str

    t : str

    Returns
    -------
    out : int

    Examples
    --------
    >>> find_the_difference("abcd", "abcde")
    'e'

    Explanation: 'e' is the letter that was added.

    >>> find_the_difference("", "y")
    'y'
    """
    s_dic = Counter(s)
    t_dic = Counter(t)
    for char in t_dic:
        if not s_dic[char] == t_dic[char]:
            return char
